[package]
name = "bevy_talks"
version = "0.1.1-dev"
edition = "2021"
description = "A framework for creating interactive conversations with Bevy."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/giusdp/bevy_talks"

[dependencies]
bevy = { version = "0.11", default-features = false, features = ["bevy_asset"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
petgraph = "0.6"
jsonschema = "0.17"

[dev-dependencies]
