[package]
name = "bevy_talks"
version = "0.1.0"
edition = "2021"
description = "A framework for creating interactive conversations with Bevy."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/giusdp/bevy_talks"

[dependencies]
bevy = {version = "0.9.1", default-features = false, features = ["bevy_asset"]}
thiserror = "1.0.39"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
log = "0.4.17"
petgraph = "0.6.3"

[dev-dependencies]
assert_fs = "1.0.10"
predicates = "2.1.5"

