[package]
name = "bevy_talks"
version = "0.1.0"
edition = "2021"
description = "A framework for creating interactive conversations with Bevy."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/giusdp/bevy_talks"

[dependencies]
bevy = { version = "0.11.0", default-features = false, features = [
    "bevy_asset",
] }
thiserror = "1.0.44"
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
log = "0.4.19"
petgraph = "0.6.3"

[dev-dependencies]
assert_fs = "1.0.13"
predicates = "3.0.3"
