[package]
name = "bevy_talks"
version = "0.3.1"
edition = "2021"
description = "A Bevy plugin to write dialogues for your characters to say and do things, together with player choices."
repository = "https://github.com/giusdp/bevy_talks"
homepage = "https://github.com/giusdp/bevy_talks"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "plugin", "dialogues", "dialogs"]
exclude = ["assets/", ".github/", "examples/"]


[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
] }
thiserror = "1.0"
serde = { version = "1" }
serde_ron = { version = "0.8", package = "ron" }
petgraph = "0.6"

[dev-dependencies]
bevy = "0.12"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "choices"
path = "examples/choices.rs"

[[example]]
name = "full"
path = "examples/full.rs"

[[example]]
name = "ingame"
path = "examples/ingame.rs"
