[package]
name = "bevy_talks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
thiserror = "1.0.38"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
log = "0.4.17"
petgraph = "0.6.3"

[dev-dependencies]
assert_fs = "1.0.10"
predicates = "2.1.5"

