name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Ubuntu dependencies
        run: sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Setup | Toolchain (clippy)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: clippy

      -  name: Annotate commit with clippy warnings
         uses: actions-rs/clippy-check@v1
         with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Setup | Toolchain (rustfmt)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: rustfmt

      - name: Lint | Rustfmt
        run: cargo fmt -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Setup | Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Build
        run: cargo build

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Setup | Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Test
        run: cargo test
